### ISSUE TITLE
Gravity Problem. 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [Kaopiz/KProgressHUD#13]
I have used this library, it awesome and easy but There is no gravity control function. 
In lollipop and marshmallow by default it appears at the center left side of the screen . How can i manage to bring it in center ?

**Comment by tuanna-hsp** [comment]
Thank for the feedback, I will check it.

**Comment by tuanna-hsp** [comment]
@ch-muhammad-adil Can you attach a screenshot and your code implementation. I have checked but couldn't recreate it.

**Comment by ch-muhammad-adil** [comment]
Can you see ?

**Comment by tuanna-hsp** [comment]
I have checked on Marshmallow but it appeared in center, not center-left.

**Comment by ch-muhammad-adil** [comment]
Here you can see

![screenshot_2016-02-23-09-09-38](https://cloud.githubusercontent.com/assets/8264639/13241555/f598c7ee-da0d-11e5-8cd9-f8719a625b8e.png)

**Comment by ch-muhammad-adil** [comment]
hud = KProgressHUD.create(TextPostScreen.this)
                .setStyle(KProgressHUD.Style.ANNULAR_DETERMINATE)
                .setLabel("Posting...")
                .setMaxProgress(100);

**Comment by ch-muhammad-adil** [comment]
I found similar issue in another version as well. 

let me recommend you one thing 
add another function which will set the gravity just like 

hud.getWindow().setGravity(Gravity.CENTER);

getWindow() will be returning parent view of this dialog. hope so it works.

**Comment by tuanna-hsp** [comment]
Thank you, i will try :+1:

**Comment by ch-muhammad-adil** [comment]
How long I should wait ? I was about to develop custom progressdialog. If you can make this change within 1 or 2 hours it will be helpful as I am facing same issue. I have requirements just like iOS .

**Comment by tuanna-hsp** [comment]
I'm pushing it right now.

**Comment by ch-muhammad-adil** [comment]
great. let me know when you done.

**Comment by tuanna-hsp** [comment]
@ch-muhammad-adil I have released 1.0.5, please check if it solve your problem

**Comment by ch-muhammad-adil** [comment]
still there ..

**Comment by tuanna-hsp** [comment]
That strange, maybe you can build the sample and see if this problem still exist.

**Comment by ch-muhammad-adil** [comment]
wait let me check your lib. :)
