### ISSUE TITLE
OnCancelled listener

### ISSUE THREAD

**Issue by rkarodia** [Kaopiz/KProgressHUD#15]
There's currently no way to set a OnCancelListener

**Comment by tuanna-hsp** [comment]
I don't see why you need a OnCancelListener but since you manually call dismiss(), you know its going to be cancelled, right? 
Or if the dialog closed by user pressing back button, you can catch the event and check if the dialog is showing.

**Comment by Shubham-Kathe** [comment]
Yes ,There is no way to handle OnCancelled Event.Activity/Fragment not recognizing onBackpress event when Dialog is shown. there should be option like Ex.
ProgressDialog   myDialog = ProgressDialog.show(
                            mContext,
                            "Please wait...",
                            "Loading the data",
                            true,
                            true,
                            new DialogInterface.OnCancelListener(){
                                @Override
                                public void onCancel(DialogInterface dialog) {
                                    Log.d(TAG,"onCancel");
                                    objName.cancel(true);
                                }
                            }
                    );
