### ISSUE TITLE
Dismiss the KPProgressHUD Programatically

### ISSUE THREAD

**Issue by MuthuEphron** [Kaopiz/KProgressHUD#16]
Can't dismiss the KPProgressHUD in my application Please Help me...?

` KProgressHUD.create(SearchCompany.this).setStyle(KProgressHUD.Style.SPIN_INDETERMINATE)
                                    .setLabel("Please Wait").setCancellable(true).show();`

**Comment by tuanna-hsp** [comment]
You can just save the HUD reference and call dismiss() on it later
`
KProgressHUD hud = KProgressHUD.create(SearchCompany.this).setStyle(KProgressHUD.Style.SPIN_INDETERMINATE) .setLabel("Please Wait").setCancellable(true);

hud.show();
hud.dismiss();
`
