### ISSUE TITLE
Add a AnimationDrawable to a CustomView

### ISSUE THREAD

**Issue by YBthebest** [Kaopiz/KProgressHUD#17]
Hi,

thanks for this awesome tool.

I was just wondering if it was possible to add an AnimationDrawable to a CustomView? I want to animate a couple of images to create my own custom loading HUD...

Thanks

**Comment by tuanna-hsp** [comment]
Yes, you can.
I have updated the sample to demonstrate `AnimationDrawable` use.
```java
ImageView imageView = new ImageView(this);
imageView.setBackgroundResource(R.drawable.spin_animation);
AnimationDrawable drawable = (AnimationDrawable) imageView.getBackground();
drawable.start();
hud = KProgressHUD.create(this)
                        .setCustomView(imageView)
                        .setLabel("This is a custom view");
```

**Comment by YBthebest** [comment]
Hi,
thanks for the answer.

This gets me the following crash:
```
Fatal Exception: java.lang.ClassCastException
android.graphics.drawable.StateListDrawable cannot be cast to android.graphics.drawable.AnimationDrawable
```

Any idea why?

**Comment by tuanna-hsp** [comment]
You are using StateListDrawable, not AnimationDrawable.
Check your animation resource file, it should be like this:
```
<?xml version="1.0" encoding="utf-8"?>
<animation-list
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/selected"
    android:oneshot="false">

    <item android:drawable="@drawable/frame_001" android:duration="50"/>
    <item android:drawable="@drawable/frame_002" android:duration="50"/>
    <item android:drawable="@drawable/frame_003" android:duration="50"/>
    <item android:drawable="@drawable/frame_004" android:duration="50"/>
    <item android:drawable="@drawable/frame_005" android:duration="50"/>
</animation-list>
```

**Comment by YBthebest** [comment]
Thanks.
Crazily enough, I get this error, even though we're talking about about 8 images of max 10kb each. How on earth is that possible?
`Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 37210012 byte allocation with 4871080 free bytes and 4MB until OOM`

**Comment by tuanna-hsp** [comment]
You should check the size of each image. 
Android load entire image as bitmap into memory. If you has an  1000x1000 image and size 10kb (maybe it compressed), when loaded memory it is 1000x1000x4 ~ 4Mb.
You should not put your images in `drawable` folder (which will easily produce above problem), but with density specific folder, like `drawable-xxhdpi` (depend on the size of your images), the Android SDK build tools will automatically scale your images for other densities.
Try putting your images in one of the below directory and see if which one is best for you
drawable-hdpi
drawable-xhdpi
drawable-xxhdpi
drawable-xxxhdpi

**Comment by YBthebest** [comment]
Thanks a lot for the tips, it worked perfectly. Cheers!
