### ISSUE TITLE
Feature request: add grace time api

### ISSUE THREAD

**Issue by gengjiawen** [Kaopiz/KProgressHUD#18]
Can we get a feature like this, thanks.

**Comment by tuanna-hsp** [comment]
Can you describe a usecase where this feature will benefit?

**Comment by gengjiawen** [comment]
When we deal with very quick http response (e.g. some http request can finish within 200ms), showing the dialog in such short time seems not comforting.
I think adding this api will make good user expirence.

**Comment by evgeny-sureev** [comment]
Hello. I just submitted a pull request with this functionality.

**Comment by tuanna-hsp** [comment]
@evgeny-sureev Thank for your help. I have reviewed and merged your PR.
