### ISSUE TITLE
not attached to window manager

### ISSUE THREAD

**Issue by YinkerBoy** [Kaopiz/KProgressHUD#27]
exception：not attached to window manager
suggest：
 public void dismiss() {
        if (mContent！=null && !(Activity)mContext.isFinish() &&mProgressDialog != null && mProgressDialog.isShowing()) {
            mProgressDialog.dismiss();
        }
    }

**Comment by tuanna-hsp** [comment]
Thank you for reporting.
I will implement the fix in the next release.

**Comment by jschmid** [comment]
@tuanna-hsp when do you think you will release a version with this fix?
Thanks !

**Comment by tuanna-hsp** [comment]
I totally forgot about this. Will try as soon as I can, possibly this week.
Sorry.

**Comment by jschmid** [comment]
Great, thanks !
