### ISSUE TITLE
Why showing HUD hides keyboard?

### ISSUE THREAD

**Issue by ControlAdad** [Kaopiz/KProgressHUD#43]
I use code below to show progress :

```
hud=KProgressHUD.create(context)
                .setStyle(KProgressHUD.Style.SPIN_INDETERMINATE)
                .setAnimationSpeed(2)
                .setDimAmount(Constants.HUD_DIM_AMOUNT)
                .setMaxProgress(100);
hud.show();
```

Why this hides device keyboard? I want keyboard to be visible.

Thanks

**Comment by tuanna-hsp** [comment]
The hud is basically a customized Dialog, so that's the default behaviour.
Looking into configuring the dialog soft input mode might be some help but I don't know for sure though.
