### ISSUE TITLE
how to change the color of progress bar?

### ISSUE THREAD

**Issue by shakeelnasrullah** [Kaopiz/KProgressHUD#64]

**Comment by tuanna-hsp** [comment]
Currently there is no method to change the progress bar color. But you can always import `KProgressHUD` into your project and add the method yourself.

**Comment by shakeelnasrullah** [comment]
> Currently there is no method to change the progress bar color. But you can always import `KProgressHUD` into your project and add the method yourself.

Thanks for your reply. I have change the color after importing it.  Thumbs up.
