### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by passsy** [Kaopiz/KProgressHUD#9]
![](https://media3.giphy.com/media/xTiTnIsgBD1elr714I/200.gif)

Could you give some insights why this library is a good idea?

I just leave this here: 
- https://www.google.com/design/spec/components/progress-activity.html#
- https://www.google.com/design/spec/components/dialogs.html#

**Comment by tuanna-hsp** [comment]
That's an interesting question :)
When we do outsourcing, there are often times when our clients only give design for iOS, and the Android version must follow the same spec. 
We created it for our work, and maybe for the others who happens in the same situation as us spend less time customizing.
